
[general]
	#The material blacklist of this module.
	materialBlacklist = ["Abyssum", "Aurorium", "Dilithium", "Draconium", "Duranite", "Eezo", "Jauxum", "Iridium", "Karmesine", "Osram", "Ovium", "Osmium", "Palladium", "Platinum", "Prometheum", "Tiberium", "Titanium", "Tungsten", "Valyrium", "Uru", "Vibranium"]

