
[general]
	#The material blacklist of this module.
	materialBlacklist = ["UUMatter", "Amethyst", "AstralStarmetal", "DiamondFake", "ElvenElementium", "Energium", "EnrichedGold", "FoolsGold", "Manasteel", "RefinedIron", "Terrasteel", "Gaia", "Unstable"]

